/* eslint-disable react/no-unescaped-entities */
import { SiteTitle } from '../components/SiteTitle';
import { Nav } from '../components/Nav';
import Head from 'next/head';

const Code = () => {
	return (
		<>
			<section className="siteHeader">
				<Head>
					<title>Edward's Info Site</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/code.ico" />
				</Head>
				<SiteTitle />
				<Nav />
			</section>
			<section className="sitePage">
				<p>code examples will appear here</p>
			</section>
		</>
	);
};

export default Code;
