/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Index.module.scss';
import { Nav } from '../components/Nav';
import { SiteTitle } from '../components/SiteTitle';

const Home: NextPage = () => {
	return (
		<>
			<section className="siteHeader">
				<Head>
					<title>Edward's Info Site</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/code.ico" />
				</Head>
				<SiteTitle />
				<Nav />
			</section>
			<section className="sitePage">
				<p>image goes here</p>
			</section>
		</>
	);
};

export default Home;
