/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { Nav } from '../components/Nav';
import { SiteHeader } from '../components/SiteHeader';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Edward's Info Site</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/code.ico" />
			</Head>

			<SiteHeader />
			<Nav />

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to Edward's Next.js site.
				</h1>

				<div className={styles.grid}>
					<a
						className={styles.card}
						href="http://edwardtanguay.vercel.app/howtos"
					>
						<h2>Howtos</h2>
						<p>
							Edward's Howtos - instructions on how to do many
							things{' '}
						</p>
					</a>
					<a
						className={styles.card}
						href="http://edwardtanguay.vercel.app/flashcards"
					>
						<h2>Flashcards</h2>
						<p>
							Edward's Flashcards - various infos Edward has
							collected
						</p>
					</a>
				</div>
			</main>
		</div>
	);
};

export default Home;
